---
 - name: Downloading spark
   become: yes
   command: wget http://www-us.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz


 - name: Extracting the spark file
   become: yes
   shell: tar -xvf spark-2.3.0-bin-hadoop2.7.tgz
   args:
     chdir: /home/ec2-user


 - name: Moving the spark file 
   become: yes
   command: mv /home/ec2-user/spark-2.3.0-bin-hadoop2.7 /usr/local/spark


 - name: Remove the extracted file
   become: yes
   command: rm -rf spark-2.3.0-bin-hadoop2.7

 - name: Remove the downloaded spark.tgz
   become: yes
   command: rm -rf spark-2.3.0-bin-hadoop2.7.tgz
