---
# - name: slaves file make
#   file:
#     path: /usr/local/spark/conf/slaves
#
#     state: touch
 - name: Copying slaves template to slave
   copy:
     src: /usr/local/spark/conf/slaves.template
     dest: /usr/local/spark/conf/slaves
     owner: ec2-user
     mode: 0644

 - name: put ips in file
   lineinfile:
     path: /usr/local/spark/conf/slaves
     line: '{{item}}'
   with_items:
       - '{{ groups["slaves"] }}'


 - name: Changing permissions of slaves file
   become: yes
   shell: chown --reference=slaves.template slaves
   args:
     chdir: /usr/local/spark/conf


 - name: Start the master 
   shell: sudo ./start-master.sh
   args:
     chdir: /usr/local/spark/sbin
 
 - name: Start the slaves
   shell: ./start-slaves.sh
   args:
     chdir: /usr/local/spark/sbin

